### ISSUE TITLE
디자인시스템 컴포넌트들 tab index 넣기

### ISSUE THREAD

**Issue by dladncks1217** [woowacourse-teams/2023-hang-log#171]
### 📄 Describe

웹 접근성 위해 디자인시스템 컴포넌트들 tab index 넣기

### ✅ Tasks

웹 접근성 위해 디자인시스템 컴포넌트들 tab index 넣기

**Comment by ashleysyheo** [comment]
Toggle이랑 Tab 컴포넌트 웹 접근성 개선하는거 제가 했어요! TripsPage만 작업해주시면 될 것 같아요!!

**Comment by dladncks1217** [comment]
흑흑 아파서 미안합니다 감사해요
