### ISSUE TITLE
비용 범위 제한

### ISSUE THREAD

**Issue by wonyongChoi05** [woowacourse-teams/2023-hang-log#338]
### 🐞 버그 설명

정수형 이상의 범위로 비용을 측정했을 때 비용이 수정되지 않네요. 혹여나 애슐리가 좋아하는 네이마르같은 사람들이 행록 서비스를 쓴다면 많이 불편할 것 같아요!

### ✅ 예상 결과

ㅇ

### ❗ 실제 결과

제가 쓴 일정이 어디갔는지 모르겠어요

### 💻 버그 시뮬레이션

일정 등록 후 정수 범위 밖의 가격으로 수정

**Comment by shin-mallang** [comment]
음수도 입력돼요!
