### ISSUE TITLE
Trip 수정 시 image url null 값 허용 

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#389]
### 🔨 Describe

#342 
위와 같은 버그로 Trip 수정 시 image url null 값을 허용해줘야 합니다.

### ✅ Tasks

- [ ] TripUpdateRequest DTO에서 null 값 허용
- [ ] null일 경우에 default image 로 변경

**Comment by wonyongChoi05** [comment]
저는 왜 assign 등록 안해주시죠??
