### ISSUE TITLE
CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#5]
### 📄 Describe

백엔드 CI/CD 파이프라인 구축 (개인)

### ✅ Tasks

- [x] CI/CD 설계
- [x] CI/CD 구축

### 🙋🏻 More

- 프론트와 논의 사항 있는지 확인 필요
- [관련 노션 정리 문서](https://www.notion.so/CI-CD-2801f22a9b854f48afb25c57d10aed3a)

**Comment by jjongwa** [comment]
일주일동안 고생 많으셨습니다~
