### ISSUE TITLE
마이페이지 수정 시 이미지만 변경된 경우 중복된 닉네임 예외 발생 

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#573]
### 🐞 버그 설명

이미지만 변경된 경우 중복 닉네임 에러가 발생합니다 

### ✅ 예상 결과

이미지만 변경된 경우에는 마이페이지 수정이 가능하도록 합니다.

### ❗ 실제 결과

이미지만 변경된 경우 중복 닉네임 에러가 발생합니다 

### 💻 버그 시뮬레이션

마이페이지 수정 -> 이미지 변경 -> 수정하기 버튼 -> 닉네임 중복 에러

### 🙋🏻 More

굉장한 홍고 🍊

**Comment by LJW25** [comment]
#576
