### ISSUE TITLE
톰캣 스레드 설정

### ISSUE THREAD

**Issue by mcodnjs** [woowacourse-teams/2023-hang-log#601]
### 🤔 Describe

톰캣 스레드 설정을 합니다.

### ✅ Tasks

- [x] maxConnection
- [x] maxThread
- [x] accept count

**Comment by LJW25** [comment]
기존의 설정을 유지하는 방향으로 결정.
부하테스트 결과와 설정 유지 이유는 노션/부하테스트 페이지 참고
